config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'high_voltage/pages#show', id: 'index'
  
  resources :posts
  
  devise_for :authors

  namespace :admin do
    get '', to: 'posts#index'
    resources :posts
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :authenticate_author!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.all
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to admin_path, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: admin_post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to admin_path, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to admin_path, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :excerpt, :body)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at desc')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :excerpt, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for([:admin, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Cím" %><br>
    <%= f.text_area :title, cols: "100", rows: "1" %>
  </div>
  <div class="field">
    <%= f.label "Kivonat" %><br>
    <%= f.text_area :excerpt, cols: "100", rows: "5" %>
  </div>
  <div class="field">
    <%= f.label "Szöveg" %><br>
    <%= f.cktext_area :body %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Mentés" %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<div class="container">
	<h1>Cikk szerkesztése</h1>

	<%= render 'form' %>
	<br>
	<%= link_to 'Megtekintés', admin_post_path %> |
	<%= link_to 'Vissza', admin_path %>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="pull-left">Admin</h1>
    <div class="admin pull-right"> 
      <% if author_signed_in? %>
        Bejelentkezve: <strong><%= current_author.email %></strong>.
        <%= link_to "Kijelentkezés", destroy_author_session_path, method: :delete  %>
      <% else %>
        <%= link_to "Bejelentkezés", new_author_session_path %>
      <% end %>
    </div>  
  </div>
  <table class="table table-striped datatable">
    <thead>
      <tr>
        <th>Cím</th>
        <th>Létrehozva</th>
        <th>Frissítve</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.created_at.strftime("%Y %m %d") %></td>
          <td><%= post.updated_at.strftime("%Y %m %d") %></td>
          <td><%= link_to 'Megtekintés', admin_post_path(post) %>
              <%= link_to 'Szerkesztés', edit_admin_post_path(post) %>
              <%= link_to 'Törlés', admin_post_path(post), method: :delete, data: { confirm: 'Biztos törölni szeretnéd a cikket?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'Új Cikk', new_admin_post_path, method: :get, class: "btn btn-success" %>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
	<h1>Új cikk</h1>

	<%= render 'form' %>
	<br>
	<%= link_to 'Vissza', admin_path %>
</div>

app/views/admin/posts/show.html.erb
<div class="container post">
	<h2 class="text-center"><%= @post.title %></h2>

	<p>
	  <strong><%= @post.excerpt %></strong>
	</p>

	<p>
	  <%= raw(@post.body) %>
	</p>
	<div class="facebook">
		<div
		  class="fb-like"
		  data-share="true"
		  data-width="450"
		  data-show-faces="true">
		</div>
		<br>
		<div class="fb-comments" data-href="http://developers.facebook.com/docs/plugins/comments/" data-numposts="5" data-colorscheme="light" data-width="100%"></div>
	</div>
	<br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Végegyházi Horgásztó</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="fI01iY_rFRSV4vmgVq4c7NvC9_zaKIknVvzlqUq8VFU" />
</head>
<body>
<header>
	<div class="col-md-4">
		<h3><%= link_to "Végegyházi Horgásztó", "/" %></h3>
	</div>
	<div class="col-md-8">
		<ul class="list-inline pull-right">
			<li class="highlighted"><%= link_to "Információ", page_path('information') %></li>
			<li><%= link_to "Hírek", posts_path %></li>
			<li><%= link_to "Rólunk", page_path('about') %></li>
			<li><%= link_to "Tóépítés", page_path('toepites') %></li>
			<li><%= link_to "Elérhetőség", page_path('contact') %></li>
		</ul>
	</div>
</header>

<%= yield %>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '363400733827105',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/hu_HU/sdk.js#xfbml=1&appId=363400733827105&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row">
	<div class="col-md-12">
	    <h1 class="title">Rólunk</h1>
	</div>
    </div>
    <div class="row">
	<p>A Végegyházi Sporthorgász Egyesület 2010. szeptember 18-án alakult meg 23 taggal. Jelenleg 105 regisztrált tagunk van, és létszámuk egyre gyarapodik. Az egyesület nyílt, bárki beléphet, aki végegyházi kötődésű és elfogadja az egyesület alapszabályát.  Az egyesület megalakulásakor tűzte zászlajára a helyi horgásztó kialakítását és üzemeltetését, amelyet a 2015. évben meg is valósítottunk.</p>
	<p>A tevékenységünk részét képezi a horgászat törvényi feltételeinek biztosításán túl a helyi környezet védelmének szervezése. Akcióink, takarítási napjaink során a Száraz-ér környéke kiemelt figyelmet kap. Rendszeresen szervezünk konferenciát a Száraz-ér és környékének védelméről és értékeiről, valamint iskolásoknak szervezzük a Száraz-ér a mi vizünk környezetvédelmi vetélkedőt is. Működési költségeinket tagdíj bevételekből, támogatásokból, pályázati támogatásokból tudjuk fedezni. Az idei évtől a horgásztó üzemeltetése is a feladataink közé került. </p>
	<p>A Békés Megyei Horgászegyesületek Szövetsége 2010. november 24-én felvette soraiba a végegyházi horgászok egyesületét, így ettől a naptól a MOHOSZ-nak is tagjaivá lettünk. Ennek a csatlakozásnak köszönhetően lehetőségünk van arra, hogy tagjaink már a 2011-es esztendő óta helyben válthassák meg az állami horgászjegyet, a szövetségi betétlapot és a megyei szövetség területi engedélyeit. Elértük tehát, hogy sporttársainknak nem kell a környező városokba utazni csak azért, hogy kiváltsák az engedélyt.
A terveink között szerepel a horgásztó környékének kiépítése, pihenőhelyek, kiülők építése, a horgász terület komfortosabbá tétele. Természetesen ebben a munkában is támaszkodnunk kell önkénteseinkre, akik számos esetben segítették működésünket. A munkánkat közel hatvan alkalmi és 21 szerződéses önkéntes segíti. Az egyesület fontos feladata a gyermekhorgász létszám fejlesztése és további hölgyhorgászok toborzása is. A tavunk lehetővé teszi horgászversenyek rendezését, nem csak saját versenyünk rendezését tervezzük, hanem kérés esetén más szervezeteknek is biztosítunk lehetőséget.</p>
	<div class="col-md-6">
	    <%= image_tag "logo.jpg" %>
	</div>
	<div class="col-md-6">
	    <h3>Az egyesület vezetősége</h3>
	    <p>A közgyűlés öttagú elnökséget választott.</p>
	    <p><strong>Elnök:</strong>Gyovai Csanád</p>
	    <p><strong>Elnökségi tagok:</strong>Takács Béla, ifj. Gyebnár Tibor, Horváth László és Mikula István</p>
	</div>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="title">Elérhetőségünk</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1375.8845363714279!2d20.857055773130295!3d46.39380505110347!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47444b8d34d0c275%3A0x400c4290c1e53f0!2zVsOpZ2VneWjDoXph!5e0!3m2!1shu!2shu!4v1420303857340" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>
		<div class="col-md-6">
			<address class="pull-right">
				<h3>Végegyházi Sporthorgász Egyesület</h3>
				<p><strong>Nyitvatartás: </strong>06:30 - 18:30</p>
				<p><strong>Cím: </strong><span>5811 Végegyháza, Széchenyi u. 7.</span></p>
				<p><strong>E-mail: </strong><span>vssporthor@citromail.hu</span></p>
				<p><strong>Telefon: </strong><span>06 30 648 0771</span></p>
			</address>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<h1 id="main-title"><span>Végegyházi Horgásztó</span></h1>
<ul class="list-unstyled" id="main-nav">
	<li><span><%= link_to "Hírek", posts_path %></span></li>
	<li><span><%= link_to "Rólunk", page_path('about') %></span></li>
    <li><span><%= link_to "Tóépítés", page_path('toepites') %></span></li>
	<li><span><%= link_to "Elérhetőség", page_path('contact') %></span></li>
</ul>

app/views/pages/information.html.erb
<div class="container">
    <div class="row">
	<h1 class="title">Információ</h1>
    </div>
    <div class="row">
	<h3>Árak</h3>
	<p><strong>Napijegy:</strong> 2500 Ft</p>
	<p><strong>Éves területi engedély:</strong> 25 000 Ft</p>
    </div>
    <hr/>
    <h3>Nyitvatartás</h3>
    <p>Mindennap: <strong>06:30 - 18:30</strong></p>
    <hr/>
    <h3>
	<a href="https://drive.google.com/open?id=0B025xALR4ZCROGp5azdZZjlOZFk">Horgászrend</a>
    </h3><span>(Katt a letöltésért)</span>
</div>

app/views/pages/toepites.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-12">
	 <h1 class="title">Tóépítés</h1>
	</div>
  </div>
<div>
    <h3>Horgászturizmussal a településünk fejlesztéséért</h3>
    <p>Az elmúlt évben pályázott a Végegyházi Sporthorgász Egyesület horgásztavának kialakítására, amely turisztikai fejlesztésként meg is valósulhatott, így a horgászturizmus fejlesztése az elkövetkező időszakban központi kérdés lesz az egyesület életében. Első lépésként a júliusi megnyitást követően rögtön lehetőség lesz napijegyes horgászatra, mind a belföldi, mind a külföldi horgásztársak számára.</p>
    <p>Ez után folyamatosan szervezzük azokat a kiegészítő programokat, amely szórakozást nyújthat a családosan érkezőknek, illetve azoknak a családtagoknak, akik nem hódolna a horgászat nemes hobbijának. Természetesen a tó környékét is komfortossá igyekszünk tenni, hogy a vendégek jól érezhessék magukat. A tó jól megközelíthető, hiszen aszfaltozott út vezet egészen a bejáratig, ahol parkolóhellyel várjuk az érkezőket. A horgásztársak bátran elhozhatják családtagjaikat, hiszen a környéken találhatnak maguknak szórakozást, hiszen közel van hozzánk Mezőkovácsháza, Mezőhegyes, vagy akár a fürdőjéről híres Nagybánhegyes település is. Azt reméljük, hogy a hozzánk látogatók szívükbe zárják csendes kis falunkat és a Dél-békési térséget.</p> 
    <strong>Találkozzunk Végegyházán!</strong>
  </div>
  <br>
  <div class="row"></div>
  <div class="text-center">
    <img src="http://vegegyhazibarangolo.hu/images/horgaszegyesulet/totot.jpg" height="800" alt="Darányi">
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="title">Hírek</h1>
  <% @posts.each do |post| %>
    <div class="post">
      <h3 class="post-title">
        <%= post.title %>
      </h3>
      <p>
        <%= post.excerpt %>
        <%= link_to "Tovább", post %>
      </p>
      
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container post">
	<h2 class="text-center"><%= @post.title %></h2>

	<p>
	  <strong><%= @post.excerpt %></strong>
	</p>

	<p>
	  <%= raw(@post.body) %>
	</p>
</div>